version: '3.8'

services:
  db:
    container_name: racingdb
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=racingdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - file_storage:/file_storage
volumes:
  db_data:
  file_storage:
